name: Flask CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Debug info
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Directory Contents:"
          ls -la
          echo "Environment Variable OWM_API_KEY: ${OWM_API_KEY}"

      - name: Run Flask app (test only)
        run: |
          export GITHUB_ACTIONS=true
          python main.py

